# Generated by Django 5.1.2 on 2024-12-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepeda',
            fields=[
                ('id_sepeda', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipe_sepeda', models.CharField(max_length=50)),
                ('merk_sepeda', models.CharField(max_length=50)),
                ('harga_sewa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_sepeda', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Dipinjam'), ('pemeliharaan', 'Pemeliharaan')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeliharaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pemeliharaan', models.CharField(choices=[('dijadwalkan', 'Dijadwalkan'), ('sedang', 'Sedang Pemeliharaan'), ('selesai', 'Selesai')], max_length=20)),
                ('tanggal_pemeliharaan', models.DateField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemeliharaan', to='users.admin')),
                ('sepeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeliharaan', to='users.sepeda')),
            ],
        ),
    ]
