# Generated by Django 5.1.2 on 2024-12-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sepeda_pemeliharaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stasiun',
            fields=[
                ('id_stasiun', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_stasiun', models.CharField(max_length=100)),
                ('alamat_stasiun', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sepeda',
            name='stasiun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepeda', to='users.stasiun'),
        ),
    ]
