# Generated by Django 5.1.2 on 2024-12-03 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sepeda_options_sepeda_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stasiun',
            options={'ordering': ['nama_stasiun'], 'verbose_name': 'Stasiun', 'verbose_name_plural': 'Stasiun'},
        ),
        migrations.AddField(
            model_name='stasiun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stasiun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
