# Generated by Django 5.1.2 on 2024-12-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_peminjaman_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_peminjaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='users.peminjaman'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('belum', 'Belum Dibayar'), ('lunas', 'Lunas')], default='belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status_peminjaman',
            field=models.CharField(choices=[('menunggu pembayaran', 'Menunggu Pembayaran'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu pembayaran', max_length=20),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_peminjaman',
            field=models.DateField(),
        ),
    ]
